trigger:
- main  # Adjust to the branch that triggers the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use 'windows-latest' or 'macos-latest' if needed

variables:
  BROWSER: 'chrome'  # Default browser, can be overridden
  CLUSTER: 'rc'      # Default cluster, can be overridden

stages:
- stage: BuildAndTest
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build and Execute Tests'
    steps:
    # Step 1: Checkout Code
    - task: Checkout@1
# Step 5: Build the project
    - script: |
        ./gradlew clean build
      displayName: 'Build Project'